In [1]:
import yfinance as yf
import pandas as pd

In [2]:
tickers = ["AAPL", "NVDA", "ZTS", "A", "BRK-B"]
period ="1y"

In [ ]:
all_financials = []

for ticker in tickers:
    t = yf.Ticker(ticker)
    financials = t.quarterly_financials.T
    financials.index.name = "period_end_date"
    financials = financials.reset_index()

    balance_sheet = t.quarterly_balance_sheet.T
    balance_sheet.index_name = "period_end_date"
    balance_sheet = balance_sheet.reset_index()

    financials["Ticker"] = ticker
    all_financials.append(financials)

fundamentals_raw = pd.concat(all_financials, ignore_index=True)

In [62]:
print(ticker)
t.get_earnings_dates()

BRK-B

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2026-11-07 15:00:00-05:00          5.78           NaN          NaN
2026-08-08 16:00:00-04:00          5.13           NaN          NaN
2026-08-08 08:00:00-04:00          5.13          6.03        17.40
2026-05-02 08:00:00-04:00          5.05          5.26         4.17
2026-02-28 08:00:00-05:00          5.17          4.73        -8.48
2025-11-01 08:00:00-04:00          5.73          6.25         9.00
2025-08-02 08:00:00-04:00          5.04          5.17         2.71
2025-05-03 08:00:00-04:00          4.72          4.47        -5.37
2025-02-22 08:00:00-05:00          4.19          6.73        60.69
2024-11-02 08:00:00-04:00          5.28          4.68       -11.34
2024-08-03 08:00:00-04:00          4.77          5.38        12.84
2024-05-04 08:00:00-04:00          4.90          5.20         5.99
2024-02-24 08:00:00-05:00          3.79          3.92         3.28
2023-11-04 08:00:00-04:00          4.93          4.96         0.62
2023-08-05 08:00:00-04:00          3.99          4.62        15.84
2023-05-06 08:00:00-04:00          3.50          3.69         5.59
2023-02-25 08:00:00-05:00          4.17          3.06       -26.58
2022-11-05 08:00:00-04:00          2.92          3.53        20.60
2022-08-06 08:00:00-04:00          3.34          4.21        26.05
2022-04-30 08:00:00-04:00          2.88          3.18        10.69
2022-02-26 08:00:00-05:00          2.95          3.27        10.65
2021-11-06 08:00:00-04:00          2.93          2.87        -2.04
2021-08-07 08:00:00-04:00          2.65          2.93        10.74
2021-05-01 08:00:00-04:00          2.57          3.05        18.60
2021-02-27 08:00:00-05:00          2.28          2.15        -5.74

In [49]:
data = yf.download(tickers, period=period, auto_adjust=False)
data.head()

[*********************100%***********************]  5 of 5 completed

Price        Adj Close                                                  \
Ticker               A        AAPL       BRK-B        NVDA         ZTS
Date
2025-09-05  127.725067  238.807846  499.769989  166.797852  150.430862
2025-09-08  127.110001  237.004517  493.779999  168.086136  148.890427
2025-09-09  125.244965  233.487503  492.720001  170.532867  146.967361
2025-09-10  123.131927  225.955322  490.079987  177.094131  146.604340
2025-09-11  125.721153  229.183395  496.910004  176.944321  147.771927

Price            Close                                                  ...  \
Ticker               A        AAPL       BRK-B        NVDA         ZTS  ...
Date                                                                    ...
2025-09-05  128.750000  239.690002  499.769989  167.020004  153.320007  ...
2025-09-08  128.130005  237.880005  493.779999  168.309998  151.750000  ...
2025-09-09  126.250000  234.350006  492.720001  170.759995  149.789993  ...
2025-09-10  124.120003  226.789993  490.079987  177.330002  149.419998  ...
2025-09-11  126.730003  230.029999  496.910004  177.169998  150.610001  ...

Price             Open                                                  \
Ticker               A        AAPL       BRK-B        NVDA         ZTS
Date
2025-09-05  128.720001  240.000000  506.000000  168.029999  152.899994
2025-09-08  127.480003  239.300003  499.000000  167.550003  152.500000
2025-09-09  128.100006  237.000000  492.450012  169.089996  151.410004
2025-09-10  125.919998  232.190002  490.000000  176.639999  149.000000
2025-09-11  125.510002  226.880005  489.329987  179.679993  149.779999

Price        Volume
Ticker            A      AAPL    BRK-B       NVDA      ZTS
Date
2025-09-05  1633200  54870400  4222900  224441400  1895900
2025-09-08  2136200  48999500  5146300  163769100  3313000
2025-09-09  1470300  66313900  3748700  157548400  1952600
2025-09-10  1669500  83440800  5561600  226852000  2734300
2025-09-11  1474100  50208600  3669000  151159300  3194000

[5 rows x 30 columns]

In [55]:
for ticker in tickers:
        ticker_data = data.xs(ticker, axis=1, level="Ticker").reset_index()
        rows = [
            (ticker, row["Date"].strftime("%Y-%m-%d"),
             row["Open"], row["High"], row["Low"], row["Close"],
             row["Adj Close"], int(row["Volume"]))
            for _, row in ticker_data.iterrows()
        ]

ticker_data

Price,Date,Adj Close,Close,High,Low,Open,Volume
0,2025-09-05,499.769989,499.769989,507.660004,497.750000,506.000000,4222900
1,2025-09-08,493.779999,493.779999,499.649994,493.459991,499.000000,5146300
2,2025-09-09,492.720001,492.720001,496.850006,491.720001,492.450012,3748700
3,2025-09-10,490.079987,490.079987,491.700012,486.269989,490.000000,5561600
4,2025-09-11,496.910004,496.910004,497.239990,489.029999,489.329987,3669000
...,...,...,...,...,...,...,...
247,2026-08-31,504.029999,504.029999,505.299988,502.200012,504.059998,5127900
248,2026-09-01,502.329987,502.329987,506.750000,501.269989,506.000000,4839100
249,2026-09-02,505.239990,505.239990,508.929993,502.600006,503.459991,3298400
250,2026-09-03,508.130005,508.130005,508.950012,505.209991,506.600006,3847300
251,2026-09-04,506.029999,506.029999,507.500000,504.299988,505.309998,3277400